[package]
name = "rustblockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
ripemd160 = "0.10.0"
secp256k1 = { version = "0.30.0", features = ["std", "rand", "serde"] }
sha2 = "0.10.8"
