[package]
name = "core_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
ripemd = "0.1.3"
sha2 = "0.10.8"
base58 = "0.2.0"
secp256k1 = { version = "0.30.0", features = ["std", "rand", "serde"] }

[lib]
crate-type = ["cdylib", "rlib"]
